[package]
name = "MoveTableExtension"
version = "1.0.0"

[addresses]
Std = "_"
Extensions = "_"

[dev-addresses]
Std = "0x1"
Extensions = "0x2"

[dependencies]
MoveStdlib = { local = "../../move-stdlib" }
